### ISSUE TITLE
Yo, não tenho maneira de te mandar mensagem mas...

### ISSUE THREAD

**Issue by DazzDev** [luist18/projecteuler#1]
Não eras o luís tavares que fazia intros e era programador de minecraft bukkit e assim? Sou o Unleashed, era bacano falarmos outra vez se quiseres xD Esta foi a única maneira que arranjei de falar ctg, fecha o issue qnd quiseres.

**Comment by luist18** [comment]
Adiciona-me no facebook e diz lá qualquer coisa https://www.facebook.com/luist188
